dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0'
networks:
  rinkeby:
    WETH_ADDRESS: "0xc778417E063141139Fce010982780140Aa0cD5Ab"
    verify: True
  kovan:
    verify: True
    WETH_ADDRESS: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env